### PR TITLE
Test eaj

### PR DESCRIPTION
**Pull request by enriqueacosta**
@elliotmath , another test I just thought about.

I was  meaning to edit test2.txt, but I by mistake am deleting a file `test.txt` (I deleted it in Finder by mistake). I also by mistake committed .DS_Store, since the app auto added it after I deleted the file (update Finder index).

Please inform me  I am incorrectly deleting files and that I should fix it.

### CODE REVIEW

**Review by elliotmath — CHANGES_REQUESTED** [review]
Not ok!  Why are you removing test.txt?  It's mission critical

**Comment by enriqueacosta** [comment]
Oh no! I had not noticed! 

If I revert the commits (which I see I can in the app), I would lose my work in test.txt...

I decided to go to master, create a copy of test.txt, and paste it in my branch. Will push soon

**Comment by enriqueacosta** [comment]
I recovered test.txt as described. All good now?

**Review by elliotmath — CHANGES_REQUESTED** [review]
I don't think you deleted .DS_stores

**Comment by enriqueacosta** [comment]
Good! (@elliotmath this was a test for you).

I reverted the commit because it was just the addition of that file.

Enrique

**Review by elliotmath — APPROVED** [review]
Oy.  something to look forward to

**Pull request merged**
